apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: "aiuser"
        - name: POSTGRES_PASSWORD
          value: "aipassword"
        - name: POSTGRES_DB
          value: "airag_db"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
  labels:
    app: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
      - name: rag-backend
        image: airag-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://aiuser:aipassword@db:5432/airag_db"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: google-api-key
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: rag-secrets
              key: groq-api-key
        - name: MLFLOW_TRACKING_URI
          value: "postgresql://aiuser:aipassword@db:5432/airag_db"
        volumeMounts:
        - name: pdf-data
          mountPath: /app/pdf_data
        - name: chroma-db
          mountPath: /app/chroma_db
      volumes:
      - name: pdf-data
        hostPath:
          path: /home/dicksons/projects/airag/pdf_data
      - name: chroma-db
        hostPath:
          path: /home/dicksons/projects/airag/chroma_db
---
apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort

